[package]
name = "rdbc-postgres"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdbc = { path = "../rdbc" }
postgres = "0.15.2"
