[package]
name = "rdbc"
description = "Rust DataBase Connectivity (RDBC) API"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
