[package]
name = "rdbc-odbc"
description = "RDBC-ODBC Bridge"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"
version = "0.1.6"
edition = "2018"

[dependencies]
rdbc = { path = "../rdbc", version = "0.1.6" }
async-trait = "0.1.22"
tokio-test = "0.2.0"
odbc = "0.16.1"
