[package]
name = "rdbc-mysql"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdbc = { path = "../rdbc" }
mysql = "17.0.0"