[package]
name = "rdbc-mysql"
description = " MySQL RDBC Driver"

version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"

edition = "2018"

[dependencies]
#rdbc = { path = "../rdbc" }
rdbc = "0.1.0"
mysql = "17.0.0"