name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Start database servers
      run: docker-compose up -d
    - name: Run tests
      run: cargo test --verbose
