name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start database servers
      run: docker-compose up -d
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
